var charPixels=(function(){var map={};var size=16;var canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;var ctx=canvas.getContext('2d');ctx.font='bold '+size+'px monospace';ctx.textAlign='center';ctx.textBaseline='middle';for(var c=32;c<127;c++){ctx.clearRect(0,0,size,size);ctx.fillStyle='white';ctx.fillRect(0,0,size,size);ctx.fillStyle='black';ctx.fillText(String.fromCharCode(c),size/2,size/2);var data=ctx.getImageData(0,0,size,size).data;var px=[];for(var i=0;i<data.length;i+=4){px.push(data[i]<128?1:0)}map[c]=px}return map})();

var symbolPairs={83:[36],36:[83],97:[64],64:[97,65],65:[64],79:[216,48],216:[79],48:[79,111],111:[48],73:[124,49],124:[73],49:[73,108],108:[49],90:[50],50:[90],66:[56],56:[66],71:[54],54:[71]};

var DNA=function(genome){if(genome){this.genome=genome}
this.fitness=0};DNA.prototype.genome='';DNA.prototype.spark=function(length){while(length--){this.genome+=String.fromCharCode(Math.floor(Math.random()*255))}};DNA.prototype.calcFitness=function(compare){var fit=0;this.charFitness=[];for(var i=0;i<this.genome.length;i++){var gc=this.genome.charCodeAt(i);var tc=compare.charCodeAt(i);var gp=charPixels[gc];var tp=charPixels[tc];var s=0;if(gp&&tp){var intersection=0,union=0;for(var j=0;j<tp.length;j++){if(gp[j]||tp[j])union++;if(gp[j]&&tp[j])intersection++}s=union>0?intersection/union:1;if(String.fromCharCode(gc).toLowerCase()===String.fromCharCode(tc).toLowerCase()){s=(gc===tc)?1.0:Math.min(0.95,s+0.45)}}var sp=symbolPairs[tc];if(sp){for(var k=0;k<sp.length;k++){if(gc===sp[k]){s=Math.min(0.9,s+0.5);break}}}fit+=s;this.charFitness.push(s)}
this.fitness=fit};DNA.prototype.mutate=function(rate){var newGenome='';for(var i=0;i<this.genome.length;i++){if(Math.random()>=rate){if(Math.random()>rate*0.5){newGenome+=this.genome[i]}else{var c=this.genome[i];newGenome+=c.toUpperCase()===this.genome[i]?c.toLowerCase():c.toUpperCase()}}else{var roll=Math.random();if(roll<0.25){var c=this.genome[i];newGenome+=c.toUpperCase()===this.genome[i]?c.toLowerCase():c.toUpperCase()}else if(roll<0.6){var code=Math.min(126,Math.max(32,this.genome.charCodeAt(i)+(Math.random()<0.5?1:-1)*Math.ceil(Math.random()*5)));newGenome+=String.fromCharCode(code)}else{newGenome+=String.fromCharCode(Math.floor(Math.random()*255))}}}
this.genome=newGenome};DNA.prototype.mate=function(partner,mut){var child='';for(var i=0;i<this.genome.length;i++){if(i<partner.genome.length){child+=(Math.random()<0.5?this.genome[i]:partner.genome[i])}else{child+=this.genome[i]}}
child=new DNA(child);var mut_=(this.genome==partner.genome)?mut*5:mut;child.mutate(mut_);return child}
