var Population=function(target,size,mutation){this.members=[];this.target=target;this.mutation=mutation;this.size=size;this.generationNumber=0;this.immigrationRate=0.1;this.lastTopFit=0;this.staleGens=0;this.checkPop=function(){var sum=0;for(var i=0;i<this.members.length;i++){this.members[i].calcFitness(this.target);sum+=this.members[i].fitness}
if(sum<0.5)return!0;return!1}
while(this.members.length<this.size){var entity=new DNA();entity.spark(this.target.length);this.members.push(entity)}
while(this.checkPop()){var entity=new DNA();entity.spark(this.target.length);this.members.push(entity)}};Population.prototype.getRunnerChars=function(){var top=this.getTop();var runners=[];for(var i=0;i<this.target.length;i++){var bestScore=-1,bestChar=null;for(var j=0;j<this.members.length;j++){var m=this.members[j];if(m.genome[i]!==top[i]&&m.charFitness){var score=m.charFitness[i];if(score>bestScore){bestScore=score;bestChar=m.genome[i]}}}runners.push(bestChar!==null?{char:bestChar,score:bestScore}:null)}return runners}
Population.prototype.display=function(){document.getElementById("count").innerHTML="gen "+this.generationNumber+" / mut: "+this.mutation.toFixed(3);var cf=this.members[0].charFitness;var runners=this.getRunnerChars();var chars=document.getElementsByClassName("char");for(var i=0;i<this.getTop().length;i++){var el=chars[i];el.getElementsByTagName("span")[0].innerHTML=this.getTop()[i];if(cf&&cf[i]!==undefined){el.style.opacity=0.1+0.9*cf[i]}var runnerEl=el.querySelector(".runner");if(!runnerEl){runnerEl=document.createElement("span");runnerEl.className="runner";var pc=el.getElementsByTagName("span")[0].className;runnerEl.style.transform=pc==='slant'?'skewX(-10deg)':pc==='backslant'?'skewX(10deg)':'';el.appendChild(runnerEl)}if(runners[i]){if(runnerEl.innerHTML!==runners[i].char){runnerEl.style.color=Math.random()<0.5?'rgb(223,100,54)':'rgb(92,132,178)'}runnerEl.innerHTML=runners[i].char;runnerEl.style.opacity=runners[i].score*0.5}else{runnerEl.innerHTML=''}}}
Population.prototype.complete=function(){var msg=this.generationNumber<1000?"Solved":"Failed to solve";msg+=" in "+this.generationNumber+" generations.";console.log(msg);document.getElementById("count").innerHTML=msg;var chars=document.getElementsByClassName("char");for(var i=0;i<chars.length;i++){chars[i].style.opacity=1;var r=chars[i].querySelector(".runner");if(r){r.innerHTML='';r.style.opacity=0}}setTimeout(function(){document.getElementById("count").innerHTML=""},5000)};Population.prototype.reSort=function(){for(var i=0;i<this.members.length;i++){this.members[i].calcFitness(this.target)}
this.members.sort(function(a,b){return b.fitness-a.fitness})};Population.prototype.populationControl=function(){while(this.members.length>this.size){this.members.pop()}
while(this.members.length<this.size){var entity=new DNA();entity.spark(this.target.length);this.members.push(entity)}};Population.prototype.getTop=function(){return this.members[0].genome};Population.prototype.tally=function(){var counts={};for(var i=0;i<this.members.length;i++){var g=this.members[i].genome;if(g in counts){counts[g]++}else{counts[g]=1}}
return counts}
Population.prototype.generation=function(){this.populationControl();this.reSort();this.display();var matingPool=[];for(var i=0;i<this.members.length;i++){var n=Math.round(Math.pow(this.members[i].fitness/this.target.length,2)*100);for(var j=0;j<n;j++){matingPool.push(i)}}
for(var i=0;i<this.size;i++){if(Math.random()<this.immigrationRate){var immigrant=new DNA();immigrant.spark(this.target.length);this.members.push(immigrant)}else{var a=Math.floor(Math.random()*matingPool.length);var b=Math.floor(Math.random()*matingPool.length);var child=this.members[matingPool[a]].mate(this.members[matingPool[b]],this.mutation);this.members.push(child)}}
this.reSort();this.populationControl();if(this.getTop()==this.target){this.display();this.complete();return!0}
var t=this.tally();if((t[this.getTop()]/parseFloat(this.members.length))>0.2){this.mutation+=0.0002}
var topFit=this.members[0].fitness;if(topFit>this.lastTopFit+0.001){this.staleGens=0;this.lastTopFit=topFit}else{this.staleGens++}
var diversity=Object.keys(t).length/this.size;if(this.staleGens>30){this.immigrationRate=Math.min(0.35,this.immigrationRate+0.015)}else if(diversity>0.7&&topFit/this.target.length<0.7){this.immigrationRate=Math.max(0.03,this.immigrationRate-0.01)}else{this.immigrationRate+=(0.1-this.immigrationRate)*0.1}
if(this.generationNumber>1000){this.complete();return!0}
this.generationNumber++;var scope=this;setTimeout(function(){scope.generation()},50)}
