var Population=function(target,size,mutation){this.members=[];this.target=target;this.mutation=mutation;this.size=size;this.generationNumber=0;this.immigrationRate=0.1;this.lastTopFit=0;this.staleGens=0;this.stopped=false;this.checkPop=function(){var sum=0;for(var i=0;i<this.members.length;i++){this.members[i].calcFitness(this.target);sum+=this.members[i].fitness}
if(sum<0.5)return!0;return!1}
while(this.members.length<this.size){var entity=new DNA();entity.spark(this.target.length);this.members.push(entity)}
while(this.checkPop()){var entity=new DNA();entity.spark(this.target.length);this.members.push(entity)}};Population.prototype.getRunnerChars=function(){var top=this.getTop();var runners=[];for(var i=0;i<this.target.length;i++){var bestScore=-1,bestChar=null;for(var j=0;j<this.members.length;j++){var m=this.members[j];if(m.genome[i]!==top[i]&&m.charFitness){var score=m.charFitness[i];if(score>bestScore){bestScore=score;bestChar=m.genome[i]}}}runners.push(bestChar!==null?{char:bestChar,score:bestScore}:null)}return runners}
Population.prototype.display=function(){document.getElementById("count").innerHTML="gen "+this.generationNumber+" / mut: "+this.mutation.toFixed(3);var cf=this.members[0].charFitness;var runners=this.getRunnerChars();var chars=document.getElementsByClassName("char");for(var i=0;i<this.getTop().length;i++){var el=chars[i];el.getElementsByTagName("span")[0].innerHTML=this.getTop()[i];if(cf&&cf[i]!==undefined){el.style.opacity=0.1+0.9*cf[i]}var runnerEl=el.querySelector(".runner");if(!runnerEl){runnerEl=document.createElement("span");runnerEl.className="runner";var pc=el.getElementsByTagName("span")[0].className;runnerEl.style.transform=pc==='slant'?'skewX(-10deg)':pc==='backslant'?'skewX(10deg)':'';el.appendChild(runnerEl)}if(runners[i]){if(runnerEl.innerHTML!==runners[i].char){runnerEl.style.color=Math.random()<0.5?'rgb(223,100,54)':'rgb(92,132,178)'}runnerEl.innerHTML=runners[i].char;runnerEl.style.opacity=runners[i].score*0.5}else{runnerEl.innerHTML=''}}
this.updateDebug(runners)}
Population.prototype.updateDebug=function(runners){var panel=document.getElementById('debug-panel');if(!panel||!panel.classList.contains('open'))return;var cf=this.members[0].charFitness;var top=this.getTop();var charsEl=document.getElementById('debug-chars');if(charsEl.children.length!==this.target.length){charsEl.innerHTML='';for(var i=0;i<this.target.length;i++){var s=document.createElement('div');s.className='dc';s.innerHTML='<div class="dc-target">'+this.target[i]+'</div><div class="dc-best"></div><div class="dc-bar"><div class="dc-fill"></div></div><div class="dc-runner"></div><div class="dc-score"></div>';charsEl.appendChild(s)}}var colors=['rgb(223,100,54)','rgb(92,132,178)'];var slots=charsEl.getElementsByClassName('dc');for(var i=0;i<this.target.length;i++){var score=cf&&cf[i]!==undefined?cf[i]:0;var best=slots[i].querySelector('.dc-best');best.textContent=top[i];best.style.opacity=0.15+0.85*score;slots[i].querySelector('.dc-fill').style.width=Math.round(score*100)+'%';var re=slots[i].querySelector('.dc-runner');if(runners&&runners[i]){if(re.textContent!==runners[i].char)re.style.color=colors[i%2];re.textContent=runners[i].char;re.style.opacity=runners[i].score*0.85}else{re.textContent=''}slots[i].querySelector('.dc-score').textContent=Math.round(score*100)+'%'}var t=this.tally();var div=Math.round(Object.keys(t).length/this.size*100);document.getElementById('d-gen').textContent='gen '+this.generationNumber;document.getElementById('d-mut').textContent='mut '+this.mutation.toFixed(3);document.getElementById('d-imm').textContent='immigr '+(this.immigrationRate*100).toFixed(0)+'%';document.getElementById('d-div').textContent='unique '+div+'%';document.getElementById('d-stale').textContent='stale '+this.staleGens}
Population.prototype.complete=function(){var msg=this.generationNumber<1000?"Solved":"Failed to solve";msg+=" in "+this.generationNumber+" generations.";console.log(msg);document.getElementById("count").innerHTML=msg;var chars=document.getElementsByClassName("char");for(var i=0;i<chars.length;i++){chars[i].style.opacity=1;var r=chars[i].querySelector(".runner");if(r){r.innerHTML='';r.style.opacity=0}}setTimeout(function(){document.getElementById("count").innerHTML=""},5000)};Population.prototype.reSort=function(){for(var i=0;i<this.members.length;i++){this.members[i].calcFitness(this.target)}
this.members.sort(function(a,b){return b.fitness-a.fitness})};Population.prototype.populationControl=function(){while(this.members.length>this.size){this.members.pop()}
while(this.members.length<this.size){var entity=new DNA();entity.spark(this.target.length);this.members.push(entity)}};Population.prototype.getTop=function(){return this.members[0].genome};Population.prototype.tally=function(){var counts={};for(var i=0;i<this.members.length;i++){var g=this.members[i].genome;if(g in counts){counts[g]++}else{counts[g]=1}}
return counts}
Population.prototype.generation=function(){if(this.stopped)return;this.populationControl();this.reSort();this.display();var matingPool=[];for(var i=0;i<this.members.length;i++){var n=Math.round(Math.pow(this.members[i].fitness/this.target.length,2)*100);for(var j=0;j<n;j++){matingPool.push(i)}}
for(var i=0;i<this.size;i++){if(Math.random()<this.immigrationRate){var immigrant=new DNA();immigrant.spark(this.target.length);this.members.push(immigrant)}else{var a=Math.floor(Math.random()*matingPool.length);var b=Math.floor(Math.random()*matingPool.length);var child=this.members[matingPool[a]].mate(this.members[matingPool[b]],this.mutation);this.members.push(child)}}
this.reSort();this.populationControl();if(this.getTop()==this.target){this.display();this.complete();return!0}
var t=this.tally();if((t[this.getTop()]/parseFloat(this.members.length))>0.2){this.mutation+=0.0002}
var topFit=this.members[0].fitness;if(topFit>this.lastTopFit+0.001){this.staleGens=0;this.lastTopFit=topFit}else{this.staleGens++}
if(this.staleGens>50){var cf=this.members[0].charFitness;var stuck=[];if(cf){for(var si=0;si<cf.length;si++){if(cf[si]<0.99)stuck.push(si)}}if(stuck.length>0){var pn=Math.floor(this.size*0.2);for(var si=this.size-pn;si<this.size;si++){var g=this.members[si].genome.split('');var p=stuck[Math.floor(Math.random()*stuck.length)];g[p]=String.fromCharCode(32+Math.floor(Math.random()*95));this.members[si]=new DNA(g.join(''))}}this.staleGens=0;this.immigrationRate=0.1}else if(this.staleGens>20){this.immigrationRate=Math.min(0.35,this.immigrationRate+0.015)}else{this.immigrationRate+=(0.1-this.immigrationRate)*0.1}
if(this.generationNumber>1000){this.complete();return!0}
this.generationNumber++;var scope=this;setTimeout(function(){scope.generation()},50)}
